version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: builder-vibe-postgres
    environment:
      POSTGRES_DB: builder_vibe
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: